version: 2.1

jobs:
  test:
    environment:
      - GO111MODULE: "on"
      - CGO_ENABLED: "0"
      -
    working_directory: /app
    docker:
      - image: makki0205/deploy
    steps:
      - checkout
      - run:
          name: go test
          command: go test -cover -race -coverprofile=coverage.txt ./...
      - run:
          name: cove
          command: bash <(curl -s https://codecov.io/bash)

workflows:
  version: 2.1
  test:
    jobs:
      - test